spring.application.name=apigateway
server.port=8080

# Eureka Client Configuration
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Disable auto-discovery locator (using manual routes)
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

# =============================
# Manual Route Configuration
# =============================

# ---- User Service (also handles Auth) ----
spring.cloud.gateway.server.webflux.routes[0].id=authservice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://authservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=patientservice
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PATIENTSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/patient/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]= AuthenticationFilter

spring.cloud.gateway.server.webflux.routes[2].id=docterservice
spring.cloud.gateway.server.webflux.routes[2].uri=lb://DOCTERSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/doctor/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]= AuthenticationFilter

spring.cloud.gateway.server.webflux.routes[3].id=appointmentservice
spring.cloud.gateway.server.webflux.routes[3].uri=lb://APPOINTMENTSERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/appointment/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]= AuthenticationFilter